apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-platform
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: payment-platform
  template:
    metadata:
      labels:
        app: payment-platform
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ default "payment-platform" .Values.serviceAccount.name }}
      {{- else if .Values.serviceAccount.name }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
{{ toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.topologySpreadConstraints.enabled }}
      topologySpreadConstraints:
        - maxSkew: {{ .Values.topologySpreadConstraints.maxSkew }}
          topologyKey: {{ .Values.topologySpreadConstraints.topologyKey | quote }}
          whenUnsatisfiable: {{ .Values.topologySpreadConstraints.whenUnsatisfiable }}
          labelSelector:
            matchLabels:
              app: payment-platform
      {{- end }}
      containers:
        - name: payment-platform
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: payment-platform-config
            - secretRef:
                name: payment-platform-secret
          {{- with .Values.containerSecurityContext }}
          securityContext:
{{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
{{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
{{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
{{ toYaml . | nindent 12 }}
          {{- end }}
