apiVersion: v1
kind: Secret
metadata:
  name: payment-platform-secret
type: Opaque
stringData:
  DATABASE_URL: "{{ .Values.envSecret.DATABASE_URL }}"
  TOKENIZATION_SECRET: "{{ .Values.envSecret.TOKENIZATION_SECRET }}"
  ACCOUNTING_WEBHOOK_URL: "{{ .Values.envSecret.ACCOUNTING_WEBHOOK_URL }}"
