apiVersion: v1
kind: Service
metadata:
  name: payment-platform
spec:
  type: {{ .Values.service.type }}
  selector:
    app: payment-platform
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
